### PR TITLE
Update SetupMinecraft.sh

### PR DESCRIPTION
**Pull request by M-Taylor40**
Updating DownloadURL with updated download links.

### CODE REVIEW

**Comment by M-Taylor40** [comment]
Downloads are no longer using azureedge.net URLs.

**Comment by rlboyd** [comment]
Any chance of getting this merged?

**Comment by skoelle** [comment]
@M-Taylor40 start.sh needs the change too

**Comment by M-Taylor40** [comment]
Updated URLs within start.sh script.

**Comment by M-Taylor40** [comment]
@TheRemote Please can you review and merge the changes to the new URL?

**Comment by TKlerx** [comment]
Would be great if this PR could be merged.

**Comment by zbfgsp3k** [comment]
Albeit 1.21.43.01 being ahead of the current version, please get the PR merged. Thank you

**Comment by 0x233233** [comment]
To temporary solve this issues, i created a fork, patched it with the new url like M-Taylor40 has done and created a script to change the minecraft start, stop, etc. scripts to my repo. So other users have an easy solution.

https://github.com/0x233233/MinecraftBedrockServer

**Comment by TheRemote** [comment]
Accepted, thank you!

**Pull request merged**
