### PR TITLE
Fix: route command not installed by default on recent distros. Use ip…

### PR DESCRIPTION
**Pull request by ZsZs73**
Hi,
Thanks for the nice script.
I've installed it on a Debian 10 VM and found that `route` command does not exist by default.
Of course one can install `net-tools` package which contains `route`, but just to check the default route can be done by `ip ro sh | grep default` instead, without installing extra packages.
HTH.
Zsolt

### CODE REVIEW

**Comment by ZsZs73** [comment]
Oyye, just realized that `net-tools` package gets installeg by the install script, but `route` command is in `/sbin/`. `/sbin` is missing from `PATH` in Debian10.
I think that manipulating PATH is more dangerous than using `ip ro` instead of `route`

**Comment by kmpoppe** [comment]
I think this is a good idea and would remove the requirement to hard coding paths as proposed in #43 which would then be redundant.

**Comment by kmpoppe** [comment]
Fixes #36.

**Comment by TheRemote** [comment]
/sbin/ has been added to path variables in latest version.  Thanks!

**Comment by ZsZs73** [comment]
I still think that using `ip` command would be more elegant than hard coding the path of `route` command.
`ip` is available in most of the distros.  Even in the minimalistis ones.

**Pull request closed without merging**
